package exception;
class DivisionExample{
	void Dividenumber(int num,int den) {
		int res = 0;
		try {
			res = num/den;
		}catch () {
			// TODO: handle exception
		}catch (Exception e) {
			
		}
	}
}

public class exception {

	public static void main(String[] args) {
		

	}

}
